In [1]:
import pandas as pd
import numpy as np

In [2]:
#Try to create dataframe (Table)
userData = {
    "MarksA":np.random.randint(1, 100, 5),
    "MarksB":np.random.randint(50, 100, 5),
    "MarksC":np.random.randint(1, 100, 5)
}

In [3]:
userData

{'MarksA': array([35, 55, 28, 87,  3]),
 'MarksB': array([59, 75, 96, 89, 54]),
 'MarksC': array([37, 77, 15, 98, 53])}

In [4]:
df = pd.DataFrame(userData)
print(df)

   MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15
3      87      89      98
4       3      54      53


In [5]:
df.head()

MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15
3      87      89      98
4       3      54      53

In [6]:
df.head(n = 3)

MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15

In [7]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [8]:
df1 = pd.DataFrame(userData, dtype='float32')
print(df1)

   MarksA  MarksB  MarksC
0    35.0    59.0    37.0
1    55.0    75.0    77.0
2    28.0    96.0    15.0
3    87.0    89.0    98.0
4     3.0    54.0    53.0


In [9]:
df.to_csv('marks.csv')

In [10]:
myData = pd.read_csv('marks.csv')
myData

Unnamed: 0  MarksA  MarksB  MarksC
0           0      35      59      37
1           1      55      75      77
2           2      28      96      15
3           3      87      89      98
4           4       3      54      53

In [11]:
myData = pd.read_csv('marks.csv')
myData = myData.drop(columns=['Unnamed: 0'])
myData

MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15
3      87      89      98
4       3      54      53

In [12]:
myData.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   41.600000  74.600000  56.000000
std    31.461087  18.256506  32.619013
min     3.000000  54.000000  15.000000
25%    28.000000  59.000000  37.000000
50%    35.000000  75.000000  53.000000
75%    55.000000  89.000000  77.000000
max    87.000000  96.000000  98.000000

In [13]:
myData.tail(n = 3)

MarksA  MarksB  MarksC
2      28      96      15
3      87      89      98
4       3      54      53

In [14]:
#accessing row
df.iloc[3]

MarksA    87
MarksB    89
MarksC    98
Name: 3, dtype: int64

In [15]:
#accessing particular cell
df.iloc[3,1]

89

In [16]:
df.iloc[3][1]

89

In [17]:
idx = [df.columns.get_loc('MarksB'), df.columns.get_loc('MarksC')]
idx

[1, 2]

In [18]:
df.iloc[3, idx]

MarksB    89
MarksC    98
Name: 3, dtype: int64

In [19]:
df.iloc[:3, idx]

MarksB  MarksC
0      59      37
1      75      77
2      96      15

In [20]:
df.iloc[:3, 1:3]

MarksB  MarksC
0      59      37
1      75      77
2      96      15

In [21]:
df.iloc[:3, [1,2]]

MarksB  MarksC
0      59      37
1      75      77
2      96      15

In [22]:
#sort the dataframe
myData

MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15
3      87      89      98
4       3      54      53

In [23]:
myData.sort_values(by=['MarksA'], ascending=True)

MarksA  MarksB  MarksC
4       3      54      53
2      28      96      15
0      35      59      37
1      55      75      77
3      87      89      98

In [24]:
myData.sort_values(by=['MarksA'], ascending=False)

MarksA  MarksB  MarksC
3      87      89      98
1      55      75      77
0      35      59      37
2      28      96      15
4       3      54      53

In [25]:
myData.sort_values(by=['MarksC', 'MarksA'], ascending=True) #priority to C then in case of tie, A is considered

MarksA  MarksB  MarksC
2      28      96      15
0      35      59      37
4       3      54      53
1      55      75      77
3      87      89      98

In [26]:
#get a numpy array
dataArray = myData.values

In [27]:
print(myData)
print(type(myData))
print(myData.shape)

   MarksA  MarksB  MarksC
0      35      59      37
1      55      75      77
2      28      96      15
3      87      89      98
4       3      54      53
<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [28]:
print(dataArray)
print(type(dataArray))
print(dataArray.shape)

[[35 59 37]
 [55 75 77]
 [28 96 15]
 [87 89 98]
 [ 3 54 53]]
<class 'numpy.ndarray'>
(5, 3)


In [29]:
dataArray[2][2]

15

In [30]:
#numpy array to dataframe
newDf = pd.DataFrame(dataArray, dtype='int8', columns=['Phy', 'Chem', 'Math'])
newDf

Phy  Chem  Math
0   35    59    37
1   55    75    77
2   28    96    15
3   87    89    98
4    3    54    53

In [31]:
newDf.to_csv('PCM.csv', index=False)

In [32]:
pcm = pd.read_csv('PCM.csv')

In [33]:
pcm

Phy  Chem  Math
0   35    59    37
1   55    75    77
2   28    96    15
3   87    89    98
4    3    54    53

In [34]:
newDf.to_csv('PCM.csv', index=False, header=False)
pcm = pd.read_csv('PCM.csv')
print(pcm)

   35  59  37
0  55  75  77
1  28  96  15
2  87  89  98
3   3  54  53
