In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [4]:
c = np.array([[1,2,3]])
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


In [5]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [6]:
#array of zeroes
a = np.zeros((3,3))
print(a)
print(a[0][1])
print(type(a))

b = np.ones((3,2))
print(b)
print(b[1][0])
print(type(b))

#array of some constant
c = np.full((2,3), 9)
print(c)

d = np.full((2,3), "india")
print(d)

#identity matrix - size/square matrix
e = np.eye(4)
print(e)

#random matrix
rand = np.random.random((2,3))
print(rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.0
<class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]
1.0
<class 'numpy.ndarray'>
[[9 9 9]
 [9 9 9]]
[['india' 'india' 'india']
 ['india' 'india' 'india']]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.10522376 0.98007484 0.72820036]
 [0.14118207 0.03420679 0.76351238]]


In [7]:
print(rand[:,1])

[0.98007484 0.03420679]


In [8]:
rand[1, 1:] = 1 #slicing
print(rand)

[[0.10522376 0.98007484 0.72820036]
 [0.14118207 1.         1.        ]]


In [9]:
#set some rows and columns
z = np.zeros((3,3), dtype = np.int64)
z[1, : ] = 3
z[:, 2] = 7
print(z)

[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [10]:
#Datatypes
print(z.dtype)

int64


In [11]:
#Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [12]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))
print(np.sqrt(y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [13]:
#Matrix Multiplication / Dot Product
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
#Multiplication Of Vectors - Scalar
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a.dot(b))

70


In [15]:
print(a)
print(sum(a)) #Sum of all elements of the array

[1 2 3 4]
10


In [16]:
print(x)
print(np.sum(x))
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [17]:
#Stacking of arrays
b = a*2
b = b*2
print(a)
print(b)

[1 2 3 4]
[ 4  8 12 16]


In [18]:
print(a)
print(b)
np.stack((a, b), axis = 0)


[1 2 3 4]
[ 4  8 12 16]


array([[ 1,  2,  3,  4],
       [ 4,  8, 12, 16]])

In [19]:
d = np.stack((a,b), axis = 1)

In [20]:
print(d)

[[ 1  4]
 [ 2  8]
 [ 3 12]
 [ 4 16]]


In [21]:
#Reshape an array
print(d.shape)
e = d.reshape(8,1)
f = d.reshape(8,)
g = d.reshape(2, -1) #decide no of rows/columns on its own
h = d.reshape(-1, 1)
print(d)
print(e)
print(f)
print(g)
print(h)

(4, 2)
[[ 1  4]
 [ 2  8]
 [ 3 12]
 [ 4 16]]
[[ 1]
 [ 4]
 [ 2]
 [ 8]
 [ 3]
 [12]
 [ 4]
 [16]]
[ 1  4  2  8  3 12  4 16]
[[ 1  4  2  8]
 [ 3 12  4 16]]
[[ 1]
 [ 4]
 [ 2]
 [ 8]
 [ 3]
 [12]
 [ 4]
 [16]]


In [22]:
#Transpose
print(d)
e = d.T
print(e)

[[ 1  4]
 [ 2  8]
 [ 3 12]
 [ 4 16]]
[[ 1  2  3  4]
 [ 4  8 12 16]]


In [23]:
#Element wise multiplication / Hadamard Multiplication
a = np.array([[ 1, 2], [ 3, 4]])
b = np.array([[ 4, 5], [ 6, 7]])
a*b

array([[ 4, 10],
       [18, 28]])

In [24]:
#L^p norm
#L^p norm = (|x1|^p + |x2|^p + ... + |xn|^p)^(1/p)
#L^2: Euclidean Distance
#L^1: summation of absolute values of the vector
#L^1 norm = |x1| + |x2| + ... + |xn|
#L^inf (max norm): absolute value of element with highest magnitude
#L^inf norm = max(|x1|, |x2|, ... , |xn|)
x = np.array([3,-4])
lp2 = np.linalg.norm(x) #by default L^2 norm
print(lp2)
lp1 = np.linalg.norm(x, ord = 1)
print(lp1)
lpinf = np.linalg.norm(x, ord = np.inf)
print(lpinf)

5.0
7.0
4.0


In [25]:
#Determinant
a = np.array([[3,4], [1,2]])
np.linalg.det(a)

2.0000000000000004

In [26]:
#inverse
ainv = np.linalg.inv(a)
print(a)
print(ainv)
print(a.dot(ainv))

[[3 4]
 [1 2]]
[[ 1.  -2. ]
 [-0.5  1.5]]
[[1.0000000e+00 8.8817842e-16]
 [0.0000000e+00 1.0000000e+00]]


In [27]:
#pseudo inverse: inverse for those for whom inverse doesn't exist(det = 0)
#if matrix invertible, then pseudo inverse = actual inverse
a = np.array([[2,3], [2,3]])
ainv = np.linalg.pinv(a)
print(a)
print(ainv)
print(np.dot(a, ainv))

[[2 3]
 [2 3]]
[[0.07692308 0.07692308]
 [0.11538462 0.11538462]]
[[0.5 0.5]
 [0.5 0.5]]


In [28]:
#solve system of equations
#eg  10x + 15y = 14
#and 14x - 16y = -2

A = np.array([[10, 15], [14, -16]])
B = np.array([14, -2])
np.linalg.solve(A, B)

array([0.52432432, 0.58378378])