In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4] ,[4, 3, 2, 1]])
print(a)

[[1 2 3 4]
 [4 3 2 1]]


In [3]:
print(np.min(a))
print(np.max(a))

1
4


In [4]:
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[1 2 2 1]
[1 1]


In [5]:
print(np.max(a, axis = 0))
print(np.max(a, axis = 1))

[4 3 3 4]
[4 4]


In [6]:
b = np.array([1,2,3,4,5, 6])
m = sum(b)/b.size
print(m)
m = np.mean(b)
print(m)
print(np.mean(a, axis = 1))

3.5
3.5
[2.5 2.5]


In [7]:
print(np.median(b))
print(np.median(a))
print(np.median(a, axis = 0))
print(np.median(a, axis = 1))

3.5
2.5
[2.5 2.5 2.5 2.5]
[2.5 2.5]


In [8]:
#average is weighted
wts = [1,2,3,4,5,6]
print(np.average(b, weights = wts))

4.333333333333333


In [9]:
#standard deviation
c = np.array([1,5,4,2,0])
u = np.mean(c)
stdDev = np.sqrt(np.mean(abs(c-u)**2))
print(stdDev)
stdDev = np.std(c)
print(stdDev)

1.854723699099141
1.854723699099141


In [10]:
#variance
print(stdDev**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
