In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [4]:
np.random.seed(1) #if you want the same numbers to be generated
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [5]:
a = np.random.random((2,3))
print(a)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]


In [6]:
a = np.random.rand(2,3)
print(a)

[[0.44345289 0.22957721 0.53441391]
 [0.91396202 0.45720481 0.43069857]]


In [7]:
#Returns values from standard normal distribution
a = np.random.randn(2,3)
print(a)

[[ 0.8858294   0.63190187  0.04026035]
 [-0.90312288  0.17532267  0.19443089]]


In [8]:
a = np.random.randint(5,10,15)
print(a)

[5 8 7 6 5 8 6 6 8 9 5 6 8 9 7]


In [9]:
#Randonly pick one element from an array
element = np.random.choice(a)
print(element)

5
