In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [4]:
c = np.array([[1,2,3]])
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


In [5]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [6]:
#array of zeroes
a = np.zeros((3,3))
print(a)
print(a[0][1])
print(type(a))

b = np.ones((3,2))
print(b)
print(b[1][0])
print(type(b))

#array of some constant
c = np.full((2,3), 9)
print(c)

d = np.full((2,3), "india")
print(d)

#identity matrix - size/square matrix
e = np.eye(4)
print(e)

#random matrix
rand = np.random.random((2,3))
print(rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.0
<class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]
1.0
<class 'numpy.ndarray'>
[[9 9 9]
 [9 9 9]]
[['india' 'india' 'india']
 ['india' 'india' 'india']]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.12751167 0.59343155 0.60962395]
 [0.22516486 0.25481558 0.04613569]]


In [7]:
print(rand[:,1])

[0.59343155 0.25481558]


In [8]:
rand[1, 1:] = 1 #slicing
print(rand)

[[0.12751167 0.59343155 0.60962395]
 [0.22516486 1.         1.        ]]


In [9]:
#set some rows and columns
z = np.zeros((3,3), dtype = np.int64)
z[1, : ] = 3
z[:, 2] = 7
print(z)

[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [10]:
#Datatypes
print(z.dtype)

int64


In [11]:
#Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [12]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))
print(np.sqrt(y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [13]:
#Matrix Multiplication / Dot Product
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
#Multiplication Of Vectors - Scalar
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a.dot(b))

70


In [15]:
print(a)
print(sum(a)) #Sum of all elements of the array

[1 2 3 4]
10


In [16]:
print(x)
print(np.sum(x))
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [17]:
#Stacking of arrays
b = a*2
b = b*2
print(a)
print(b)

[1 2 3 4]
[ 4  8 12 16]


In [18]:
print(a)
print(b)
np.stack((a, b), axis = 0)


[1 2 3 4]
[ 4  8 12 16]


array([[ 1,  2,  3,  4],
       [ 4,  8, 12, 16]])

In [21]:
d = np.stack((a,b), axis = 1)

In [22]:
print(d)

[[ 1  4]
 [ 2  8]
 [ 3 12]
 [ 4 16]]


In [45]:
#Reshape an array
print(d.shape)
e = d.reshape(8,1)
f = d.reshape(8,)
g = d.reshape(2, -1) #decide no of rows/columns on its own
h = d.reshape(-1, 1)
print(d)
print(e)
print(f)
print(g)
print(h)

(2, 4)
[[ 1  4  2  8]
 [ 3 12  4 16]]
[[ 1]
 [ 4]
 [ 2]
 [ 8]
 [ 3]
 [12]
 [ 4]
 [16]]
[ 1  4  2  8  3 12  4 16]
[[ 1  4  2  8]
 [ 3 12  4 16]]
[[ 1]
 [ 4]
 [ 2]
 [ 8]
 [ 3]
 [12]
 [ 4]
 [16]]
